name: Tectonic build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get and run tectonic
        uses: actions/cache@v3
        run: |
          curl --proto '=https' --tlsv1.2 -fsSL https://drop-sh.fullyjustified.net |sh
          tectonic -X build

      - uses: actions/upload-artifact@v3
        with:
          name: pdfs
          path: build/default/default.pdf

      # - name: Tectonic
      #   uses: wtfjoke/setup-tectonic@v2
      #   with:
      #     github-token: ${{secrets.GITHUB_TOKEN }}
      #   run: 

